var EnemyType = [
    {
        type:0,
        textureName:"E0.png",
        HP:1,
        moveType:global.moveType.Vertical,
        scoreValue:10
    },
    {
        type:1,
        textureName:"E1.png",
        HP:2,
        moveType:global.moveType.Horizontal,
        scoreValue:20
    },
    {
        type:2,
        textureName:"E2.png",
        HP:5,
        moveType:global.moveType.Horizontal,
        scoreValue:50
    },
    {
        type:3,
        textureName:"E3.png",
        HP:10,
        moveType:global.moveType.Overlap,
        scoreValue:100
    },
    {
        type:4,
        textureName:"E4.png",
        HP:15,
        moveType:global.moveType.Random,
        scoreValue:150
    },
    {
        type:5,
        textureName:"E5.png",
        HP:20,
        moveType:global.moveType.Random,
        scoreValue:200
    }
]