var global = {
    level:1,
    life:4,
    score:0,
    sound:true,
    bulletType:{
        Ship:1,
        Enemy:2
    },
    weaponType:{
         one:1
    },
    Tag:{
        EnemyBullet:900,
        Enemy:901,
        Ship:902,
        ShipBullet:903
    },
    moveType:{
        Attack:0,
        Vertical:1,
        Horizontal:2,
        Overlap:3
    },
    AttackMode:{
        Normal:1,
        Tsuihikidan:2
    }
};