var Level1 = {
    enemies:[
        {
            ShowType:"Repeate",
            ShowTime:"00:02",
            Types:[2,2,2,2]
        }/*,
        {
            ShowType:"Once",
            ShowTime:"00:04",
            Types:[0,2,3,1,3,2]
        },
        {
            ShowType:"Once",
            ShowTime:"00:8",
            Types:[0,2,2,2,2]
        },
        {
            ShowType:"Once",
            ShowTime:"00:10",
            Types:[0,0,0,0,0,3]
        },
        {
            ShowType:"Once",
            ShowTime:"01:55",
            Types:[0,3,2,1,0,3]
        }*/
    ]
};