speed:6,
bulletSpeed:11,
HP:1,
score:0,
life:3,
flashTime:150,
bulletTypeValue:1,
bulletPowerValue:1,
shotting:false,
throwBombing:false,
canBeAttack:false,
canBeControl:false,
isThrowingBomb:false,
zIndex:3000,
maxBulletPowerValue:4,
canShot:true,
lifeUpScores:[50000,100000,150000,200000,250000,300000],

concentrationValue:0,
concentrationPowerType:"concentrationPowerType1",
isShottingConcentrationPower:false,
isConcentrated:false,
concentrationTime:2,
concentrationIsFixed:false,

appearPosition:{},
subPlanes:new Array(),
concentrationEmplacements:new Array(),
emplacements:new Array(),
concentrationTimer,
concertartionAnimation,